[ORT-1] feat: add design tokens & add `Button`
majority-elite/ort-frontend pull request #1
Opened 2024-08-09 13:53 UTC by aube-dev

## Notion Task

https://www.notion.so/team-woori/15245d18e6474a8c9bb8174b70578db9?pvs=4

## 설명

- 컬러, 텍스트 스타일을 추가했습니다.
- `Button` 컴포넌트를 구현했습니다.

2024-08-09 14:07 UTC, Godbell commented on app/styles/text.css.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
의도된 disable인가요? any로 설정되어야 하는 이유가 궁금합니다!

2024-08-09 14:33 UTC, crew852 approved these changes
참 잘했어요~

2024-08-09 14:33 UTC, crew852 commented on app/root.css.ts
> +});
globalStyle의 fontSize를 62.5%에 맞춘 의도가 궁금합니다(진짜)
이게 어떻게 작용하는 건가요?

2024-08-09 14:33 UTC, crew852 commented on app/styles/text.css.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
eslint-disable을 한 이유가 궁금하빈다(진짜루)
설명 부탁드립니다

2024-08-09 14:36 UTC, aube-dev commented on app/root.css.ts
> +});
`rem` 단위를 좀 더 편하게 사용하기 위한 트릭인데, [관련 아티클](https://velog.io/@qhflrnfl4324/html-font-size-62.5-를-적용하자)을 살펴보시면 좋을 듯합니다!

2024-08-09 14:38 UTC, aube-dev commented on app/styles/text.css.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
코드를 보면 Type Parameter인 `T`를 받고 있는데, `T`는 실제로 `Record<string, any>` 타입으로 정의되는 것이 아니라, 적어도 이 타입을 만족하면 된다는 한정 조건만 받고 있습니다. 실제 구현을 보면 `Object.keys`는 객체의 key만 가져올 뿐 value가 무엇인지에는 관심이 없으므로, value의 타입을 의미하는 `Record`의 2번째 Type Parameter에는 `any`가 들어가지 않으면 모든 케이스를 커버할 수 없습니다.
간단히 요약하면, 타입을 특정하는 것이 아니라 타입에 조건을 거는 것이기 때문에 그렇습니다!

2024-08-09 14:54 UTC, Godbell requested changes

2024-08-09 14:54 UTC, Godbell commented on app/styles/text.css.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
의도된 disable인가요? any로 설정되어야 하는 이유가 궁금합니다!

2024-08-09 14:54 UTC, Godbell commented on app/constants/style.ts
태블릿이나 모바일은 특정 디바이스에 맞춘 값인가요? 맞다면 명시하는 것도 좋을 것 같은데 어떨까요?

2024-08-09 14:54 UTC, Godbell commented on app/utils/style.ts
> +export const getRGBFromHex = (hex: string) => {
```ts
return {
  r: 0,
  g: 0,
  b: 0,
}
```
요런 형식은 어떤가요?

2024-08-09 14:54 UTC, Godbell commented on app/utils/style.ts
> +};
`getMediaQuery()`에 대해 이해하기로는, 여러 디바이스를 명시했을 때 해당 디바이스들에서는 같은 모습으로 보이도록 하는 것으로 보입니다. 최대와 최소만 뽑아내는 경우에서 언급된 케이스로 보아 `[Breakpoint.MOBILE1, Breakpoint.PC1]`과 같은 사용도 의도된 것 같은데 맞나요?

2024-08-09 14:54 UTC, Godbell commented on app/styles/theme.css.ts
> +const getColorVarsFromHex = (hex: string) => ({
사용례로 보아 `hex`는 항상 `#`로 시작하네요, type으로 `hex`의 prefix가 `#`라는 것을 명시적으로 작성하면 좋아 보입니다.

본 함수는 `Button.css.ts`에서 확인한 대로, 다음과 같은 사용법으로 보입니다.
```ts
const someCssString = `rgba(${themeVars.color.background.general.rgb}, 알파값)`
```
`rgb`의 사용 목적이 rgba에 국한되는 것 같은데, closure를 활용하여 다음과 같이 rgba 사용 반복을 없애는 것은 어떨까 합니다.
```ts
const getColorVarsFromHex = (hex, a) => {
  return {
    hex,
    rgba: (alpha) => `rgba(${getRGBFromHex(hex).join(',')},${alpha})`
  };
}

```
위와 같이 작성할 경우 `Button.css.ts`에서는 다음과 같이 활용할 수 있습니다.
```ts
themeVars.color.background.general.rgba(10)    // "rgba(255,255,255,10)"
```

2024-08-09 14:55 UTC, aube-dev commented on app/styles/text.css.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
[위 논의](https://github.com/majority-elite/ort-frontend/pull/1#discussion_r1711585350)를 참고해 주시면 됩니다!

2024-08-09 14:57 UTC, aube-dev commented on app/constants/style.ts
디자인 이야기이긴 한데, 특정 디바이스를 염두하지는 않았고 일반적인 viewport resolution 통계를 고려한 뒤 메인 화면 레이아웃이 예쁘게 나올 만한 수치로 세부조정한 결과입니다. 개발상 신경쓸 만한 매직 넘버 같은 느낌은 아니어서 따로 설명을 하지는 않았는데, 혹시 설명을 적으면 좋을 만한 것이 있을까요?

2024-08-09 14:58 UTC, aube-dev commented on app/utils/style.ts
> +export const getRGBFromHex = (hex: string) => {
괜찮기는 한데, RGB 순으로 적어야 한다는 것은 통용되는 지식이기도 하고, tuple 형태가 `.join`을 사용하기 편리할 것 같아 저렇게 구현했습니다. 혹시 더 좋은 방법이 있다면 제안 부탁드립니다!

2024-08-09 14:59 UTC, Godbell commented on app/constants/style.ts
특정 디바이스에 일부러 맞춘 것이 아니라면 따로 명시할 필요는 없어 보이네요, resolve하겠습니다 :D

2024-08-09 15:00 UTC, aube-dev commented on app/utils/style.ts
> +};
의도는 아니긴 합니다. 정확히는, 그런 케이스가 가능하다는 것은 알고 구현했으나 권장하지는 않는다는 쪽에 가깝습니다.
왜냐하면, 이론적으로 중간 부분을 건너뛰는 것과 중간 부분을 모두 명시하는 것은 결과가 동일할 수밖에 없는데, 개발자의 입장에서는 중간 부분을 모두 명시하는 것이 human error를 줄일 수 있기 때문입니다.

2024-08-09 15:01 UTC, aube-dev commented on app/styles/theme.css.ts
> +const getColorVarsFromHex = (hex: string) => ({
1. 타입을 더 엄밀하게 정의하는 것은 좋아 보입니다! 반영하겠습니다.

2024-08-09 15:10 UTC, Godbell commented on app/utils/style.ts
> +export const getRGBFromHex = (hex: string) => {
RGB 순서는 일반적이나, 선언부를 보지 않는다고 가정했을 때
```ts
color.r
color.g
color.b
```
과 같은 사용법과,
```ts
color[0]
color[1]
color[2]
```
과 같은 사용법에서, (물론 RGB 이외의 방식을 쓰는 경우는 거의 없겠지만) 직관성의 차이가 크다고 생각합니다.
다른 코드에서도 본 함수를 자주 사용한다면 `join()` 사용의 편의성을 희생하더라도 직관성을 위해 전자의 방식을 채택하는 것을 제안합니다. 코드가 다소 길어지긴 하나 `join()` 대신 `Object.values`를 통해 문자열을 합칠 수도 있고 이러한 활용은 대부분 함수화되기 때문에 크게 문제되지 않는다고 봅니다.
만약 다른 코드에서 본 함수를 사용할 일이 없다면, 유틸로 빼는 대신 일단은 `getColorVarsFromHex()`에 합치는 것도 좋다고 생각합니다.

2024-08-09 15:13 UTC, aube-dev commented on app/styles/theme.css.ts
> +const getColorVarsFromHex = (hex: string) => ({
2. 좋은 방법인 것 같지만, `createGlobalTheme`에서는 사용할 수 없는 방법입니다.
vanilla extract는 CSS Module과 같이 정적인 CSS 파일만을 생성하기 때문에, 번들 타임에만 내부 JS 코드가 실행되고 이후에는 전부 CSS 파일로 변환되어 버립니다. 따라서 `createGlobalTheme` 내에 정의된 색상들은 실제로는 다음과 비슷한 형식으로 바뀝니다.
```css
:root {
  --color-background-general-hex: #FFFFFF;
  /* ... */
}
```
따라서 `createGlobalTheme` 안에는 함수와 같이 serializable하지 않은 값은 들어갈 수 없습니다.
비슷한 해결책을 찾자면 다음과 같을 것 같은데, 어쨌든 rgb 단독 정의는 필요합니다.
```typescript
const getRGBAFromVar = (var: string, alpha: number) => `rgba(${var}, alpha)`;

const someStyle = style({
  color: getRGBAFromVar(themeVars.color.background.general.rgb),
});
```
또는 말씀해 주신 형태를 적극 채용하려면, CSS Variable을 아예 활용하지 않고 다음과 같이 JS에만 의존하는 방법도 있습니다.
```typescript
const getColorVarsFromHex = (hex, a) => {
  return {
    hex,
    rgba: (alpha) => `rgba(${getRGBFromHex(hex).join(',')},${alpha})`
  };
};

const COLOR = {
  background: {
    general: getColorVarsFromHex('#FFFFFF'),
    // ...
  },
  // ...
} as const;

const someStyle = style({
  color: COLOR.background.general.rgba(0.1),
});
```
이런 것도 좋아보이긴 한데, CSS Variable을 사용할 때와 color literal을 사용할 때의 tradeoff가 있는지는 잘 몰라서, 한 번 알아보고 다시 코멘트 달겠습니다.

2024-08-09 15:18 UTC, aube-dev commented on app/utils/style.ts
> +export const getRGBFromHex = (hex: string) => {
다음과 같이 사용 가능하기는 하나,
```typescript
const [r, g, b] = getRGBFromHex('#FFFFFF');
```
확실히 직관성의 차이가 있는 것 같기는 합니다. 사실 보통은 이렇게 굳이 Hex -> RGB 변환을 프로그램으로 하지 않고 하드코딩으로 하긴 하는데, 이왕 유틸로 되어 있으니 말씀하신 대로 직관성을 챙기는 것이 좋을 것 같네요. 조금 더 고민해보고 다시 코멘트 드리겠습니다!

2024-08-09 15:19 UTC, Godbell requested changes

2024-08-09 15:19 UTC, Godbell commented on app/utils/style.ts
> +};
휴먼 에러와 브레이크포인트 수정 시 작업을 줄이기 위한 방식으로 다음과 같은 방식은 어떨까요?
```ts
export const Breakpoint = {
  PC2: [1504, Infinity],
  PC1: [1140, 1503],
  TABLET2: [832, 1139],
  TABLET1: [728, 831],
  MOBILE2: [580, 727],
  MOBILE1: [0, 579],
} as const;
```
```ts
export const getMediaQuery = (
  minBreakpoint: readonly [number, number],
  maxBreakpoint: readonly [number, number],
) => `screen and (min-width: ${minBreakpoint[0]}px)${isFinite(maxBreapoint[1]) ? `and (max-width: ${maxBreapoint[1]}px)` : ''}`
```

2024-08-09 15:26 UTC, aube-dev commented on app/utils/style.ts
> +};
1. 개발자 입장에서는 어떤 Breakpoint가 더 큰지/작은지 대소관계를 고려해야 하는 상황보다, 어떤 breakpoint가 포함되어야 하는지 라벨만 다루어도 되는 상황이 더 직관적일 것 같습니다. 실제로 Figma 디자인 상에는 모든 화면에 어떤 breakpoint가 포함되는지 라벨이 함께 적혀 있고, 수정이 생기는 경우 이 라벨도 함께 수정될 것이므로, 어느 것이 최소/최대인지 개발자가 고민하고 작성해야 하는 것은 더 불편한 방식이 아닐까 합니다. 핵심은, 개발자가 생각을 한 번 더 하지 않고 Figma에 적혀 있는 것과 동일하게 코드를 작성해도 무방한 환경이 가장 직관적이지 않겠냐는 주장입니다.
2. 대상 breakpoint가 하나인 경우가 있습니다. 이 경우 `minBreakpoint`=`maxBreakpoint`이므로, 굳이 parameter가 2개일 필요가 없습니다.

2024-08-09 15:29 UTC, aube-dev commented on app/utils/style.ts
> +};
3. 중간 부분을 명시하는 여부에 따른 human error는 결국 코드의 구현 문제가 아니라, 개발자가 Figma에 적혀 있는 것과 다르게 한 번 더 깊게 생각하여 최대/최소를 고려하는 바람에 생긴 Figma-프론트 간의 간극에서 발생한다고 봅니다. 즉 제시해주신 코드는 오히려 개발자가 함부로 breakpoint 간 대소관계를 파악하게 만들고, 나중에 디자인 수정으로 인해 이러한 대소관계가 역전될 경우 디버깅을 하기 어렵게 만드므로 human error를 증가시키지 않을까 합니다. (중간 부분을 모두 명시하면 Ctrl+F로 어느 breakpoint가 어떤 스타일에 영향을 받는지 찾기 쉽다는 점도 있습니다.)

2024-08-09 15:31 UTC, Godbell commented on app/utils/style.ts
> +};
figma 라벨 관련 사항은 생각 못했네요, 그렇다면 함수나 브레이크포인트 객체에 figma 기획에 맞게 작성하도록 하는 주석을 다는 것으로 충분해 보입니다!

2024-08-09 15:32 UTC, aube-dev commented on app/utils/style.ts
> +};
좋습니다! 주석을 조금 보강하는 것으로 마무리할게요

2024-08-09 16:48 UTC, aube-dev commented on app/styles/theme.css.ts
> +const getColorVarsFromHex = (hex: string) => ({
고민해 보았는데, CSS Variable을 사용하는 것의 tradeoff는 결국 동적으로 바꿀 수 있는지의 여부, 즉 테마 기능에 달린 것 같습니다. (CSS Variable은 runtime에도 re-assign이 가능한데, JS 변수로 선언/계산한 값은 번들링 타임에 결과 string만이 하드코딩되어 들어가므로 불가) 지금은 다크모드 등의 테마를 전혀 고려하고 있지 않으나, 그렇다고 코드상에서 너무 static하게만 만들 경우 혹시나 기획이 변경되어 테마의 변경이 필요할 때 너무 어렵게 수정해야만 하고, 개인적으로는 CSS Variable을 사용하는 것을 포기할 만큼의 경험 차이는 없는 것 같습니다.
로직 자체는 제가 처음에 제시한 대안(`getRGBAFromVar`)과 같은데 이렇게 이름을 `rgba`로 수정해 보면 생산성도 추가 import 외에는 차이 없고 순수 css 같아 보여서 좋은 것 같은데 혹시 어떤가요?
```typescript
// app/utils/style.ts

export const rgba = (var: string, alpha: number = 1) => `rgba(${var}, ${alpha})`;
```
```typescript
import { rgba } from '@/utils/style';

const someStyle = style({
  color: themeVars.color.background.normal.hex,
  backgroundColor: rgba(themeVars.color.background.normal.rgb, 0.2),
});
```
혹은, 사실 유연성을 더 고려하면 HSLA를 도입하는 것도 고민중인데([TOAST UI의 아티클](https://ui.toast.com/posts/ko_20210402#%EC%83%89%EC%83%81-%EA%B3%84%EC%B8%B5) 참고), 이건 나중에 해도 전환 공수도 크게는 안 들 듯해서 지금은 고려하지 않으려고 합니다.

2024-08-09 16:54 UTC, aube-dev commented on app/utils/style.ts
> +export const getRGBFromHex = (hex: string) => {
고민해 보았는데, 충분히 설득이 되어 말씀하신 방식대로 수정하겠습니다!

2024-08-14 14:07 UTC, Godbell commented on app/styles/theme.css.ts
> +const getColorVarsFromHex = (hex: string) => ({
1. HSLA는 지금 고려하지 않아도 될 것 같습니다
2. `'123,23,23'`과 같은 형태의 문자열을 따로 저장하는 게 불필요해 보입니다. 결국 헥스값과 형식만 다른 정보라 쓸 때 변경하면 어떨까 싶어요

올려주신 대로 사용한다고 하면, 콤마로 연결된 문자열 대신 헥스값을 받아 처리하는 것이 좋아 보입니다.

```ts
export const rgba = (hex: string, alpha: number = 1) => {
  const {r, g, b} = getRGBFromHex(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}
```

2024-08-16 07:02 UTC, Godbell approved these changes

2024-08-16 07:04 UTC, crew852 approved these changes
내가 졌다...

2024-08-16 07:05 UTC, merged