[ORT-2] feat: add KakaoLoginButton
majority-elite/ort-frontend pull request #2
Opened 2024-08-16 08:19 UTC by crew852

맡은 태스크를 맞게 수행하는 코드를 작성했는지 잘 모르겠네요...
일단 로그인 버튼 -> 로그인 페이지 -> 리다이렉트 -> 백엔드에 code값과 state값 전달이 되게 만들어 봤습니다.
많은 도움 부탁드립니다...

2024-08-16 18:47 UTC, aube-dev requested changes

2024-08-16 18:47 UTC, aube-dev commented on app/components/KakaoLoginButton/KakaoLoginButton.tsx
> +const redirectUri = 'http://localhost:5173/oauth/kakao';
우선은 상관없지만, 제가 Env 관련 작업을 하고 나면 환경변수로 변경하면 좋을 듯합니다!

2024-08-16 18:47 UTC, aube-dev commented on app/routes/oauth.kakao.tsx.tsx
> +//HTTP 요청을 보내기 위해 axios라이브러리를 추가했습니다.
제가 API 요청 코드베이스를 작성 중인데, `axios`를 굳이 사용하지 않아도 작업이 가능할 것 같습니다.
제 작업이 끝나고 나면 그 코드베이스 기반으로 제가 수정해 놓겠습니다!

2024-08-16 18:47 UTC, aube-dev commented on app/routes/oauth.kakao.tsx.tsx
> +*/
[JSDoc](https://jsdoc.app/about-getting-started) 형태로 주석을 작성하면 좋을 듯합니다.
`/**` 이걸로 주석을 시작하면 IDE에서 자동완성 되더라구요!

2024-08-16 18:47 UTC, aube-dev commented on app/routes/oauth.kakao.tsx.tsx
> +  }, [searchParams]);
위 코멘트 반영해서 `action` -> `loader`로 변경하면 이렇게 `useEffect`로 클라이언트 단에서 실행할 필요가 없을 듯합니다. 그러면 클라이언트 사이드에 가기 전에 로그인 처리가 되기 때문에 더 빠르게 처리 가능할 것 같아요!

2024-08-16 18:47 UTC, aube-dev commented on app/routes/oauth.kakao.tsx.tsx
> +export const action: ActionFunction = async ({ request }) => {
해당 페이지에 진입하자마자 실행되어야 하는 것이기에 `action`보다는 `loader`가 적합하지 않을까 제안합니다.
[`loader`에서 search param에 접근하는 방법](https://remix.run/docs/en/main/guides/data-loading#url-search-params)을 참고하면 좋을 듯합니다!

2024-08-16 18:47 UTC, aube-dev commented on app/components/KakaoLoginButton/KakaoLoginButton.tsx
> +const getUserUUID = (): string => uuidv4();
지금은 여기서만 쓰고 있긴 하지만 일반적인 로직인 것 같아 `utils` 디렉토리에 들어가면 좋을 것 같은데 어떠신가요?

2024-08-27 07:46 UTC, crew852 commented on app/components/KakaoLoginButton/KakaoLoginButton.tsx
> +const getUserUUID = (): string => uuidv4();
합리적인 제안인 것 같네요.
적극 반영하여 수정하겠습니ㄷㅏ🫠👍

2024-08-27 07:47 UTC, crew852 commented on app/routes/oauth.kakao.tsx.tsx
> +export const action: ActionFunction = async ({ request }) => {
의견 반영하여 수정해보았습니다.
확인 후, 의도대로 되었다면 resolve 부탁드려용

2024-08-27 07:48 UTC, crew852 commented on app/routes/oauth.kakao.tsx.tsx
> +*/
jsdoc을 써본 적이 없어서 기피했답ㄴㅣ다...
수정된 주석이 올바르게 작성되었는지 확인해주시고 맞다면 resolve 부탁드려용

2024-08-27 07:56 UTC, aube-dev approved these changes
LGTM 👍

2024-08-27 07:57 UTC, aube-dev requested changes

2024-08-27 07:57 UTC, aube-dev commented on app/routes/oauth.kakao.tsx.tsx
> +  }, [searchParams]);
`loader`로 바꾸면서 이제 필요없어진 코드이니 삭제 부탁드려요!

2024-08-27 08:04 UTC, crew852 commented on app/routes/oauth.kakao.tsx.tsx
> +  }, [searchParams]);
오우...깜빡했네요!
바로 조치하겠ㅅㅡ빈다🫠

2024-08-30 07:54 UTC, aube-dev requested changes

2024-08-30 07:54 UTC, aube-dev commented on app/utils/getUUID.ts
> +};
요기 혹시 이렇게 한 이유가 있을까요? 이렇게 단순화할 수 있을 것 같아서요!
```suggestion
const getUUID = () => uuidv4();
```

2024-08-30 07:54 UTC, aube-dev commented on app/utils/getUUID.ts
> +export default getUUID;
한 파일에 하나의 함수만 넣는 방식인 것 같은데, 그러기엔 코드가 너무 짧아 보여서 그냥 `app/utils/random` 정도로만 네이밍하고, default export가 아닌 named export를 하는 게 어떨까요?

2024-08-30 07:54 UTC, aube-dev commented on package.json
> +    "uuid": "^10.0.0"
`^`을 붙이면 일관된 버전을 적용하지 않아서 예상치 못한 breaking change를 디버깅하기 어려울 수 있어요.
```suggestion
    "uuid": "10.0.0"
```

2024-08-30 07:54 UTC, aube-dev commented on package.json
> +    "@types/uuid": "^10.0.0",
```suggestion
    "@types/uuid": "10.0.0",
```

2024-08-30 07:54 UTC, aube-dev commented on app/routes/oauth.kakao.tsx.tsx
> +  }
이 코드 부분 혹시 지워주실 수 있을까요? 제가 이어서 작업하겠습니다!

2024-08-30 07:54 UTC, aube-dev commented on package.json
> +    "axios": "^1.7.4",
이 라이브러리 지워주실 수 있을까요? 제가 API 부분 작업하려고 합니다!

2024-08-30 07:56 UTC, crew852 commented on app/utils/getUUID.ts
> +};
이 부분은 저의 화살표 함수 활용 미숙이네요...
이제 보니 왜 이랬나 싶군요
바로 반영하겠습니다~

2024-08-30 08:01 UTC, crew852 commented on app/utils/getUUID.ts
> +export default getUUID;
그게 맞는 것 같긴 한데, 이 외에 이 함수와 같이 들어갈 만한 다른 함수가 생각나지 않아서 이렇게 작성했습니다.
그러나 말씀해주신 대로 이름 붙여 놓으면 나중에 뭔가 추가되어 수정을 하게 되어도 괜찮겠네요!
이것도 반영해 수정해 둘게요~

2024-08-30 08:02 UTC, crew852 commented on package.json
> +    "uuid": "^10.0.0"
오...이건 그냥 몰랐습니다
정말 위대합니다, 선생!

2024-08-30 08:21 UTC, crew852 commented on app/routes/oauth.kakao.tsx.tsx
> +  }
지우면 커밋이 불가해서 `console.log` 찍는 `try`문으로 대체해 놨습니다.
해당 부분 지우고 이어서 해주시면 될 것 같습니당~

2024-08-30 08:38 UTC, aube-dev approved these changes
LGTM 👍

2024-08-30 08:39 UTC, merged